"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import {
  fail,
  orNull,
  toInt,
  toNullableNum,
  toNum,
  type ActionResult,
} from "@/lib/persist";
import { syncJobCalendar } from "@/lib/google-calendar";
import type { CustomerType, JobStatus } from "@/lib/types";

export type JobWorkerPayload = {
  entity_id: string | null;
  regular_hours: number | string;
  regular_rate: number | string;
  travel_hours: number | string;
  travel_rate: number | string;
  other_hours: number | string;
  other_rate: number | string;
  total_pay_override: number | string | null;
  fees: { description: string | null; amount: number | string }[];
};

export type JobPayload = {
  id: string | null;
  customer_name: string | null;
  customer_phone: string | null;
  customer_type: CustomerType | null;
  service_category_id: string | null;
  lead_source_id: string | null;
  partnership_id: string | null;
  zone_id: string | null;
  status: JobStatus;
  date_of_invoice: string | null;
  arrival_date: string | null;
  arrival_time: string | null;
  estimated_duration_minutes: number | string | null;
  addresses: string[];
  total_invoice_paid: number | string;
  pos_fee_percent: number | string;
  other_job_costs: number | string;
  total_worker_payout_override: number | string | null;
  invoice_ref: string | null;
  notes: string | null;
  workers: JobWorkerPayload[];
};

export type JobSaveResult = ActionResult & { warning?: string | null };

export async function saveJob(payload: JobPayload): Promise<JobSaveResult> {
  const supabase = await createClient();

  const row = {
    customer_name: orNull(payload.customer_name),
    customer_phone: orNull(payload.customer_phone),
    customer_type: payload.customer_type || null,
    service_category_id: payload.service_category_id || null,
    lead_source_id: payload.lead_source_id || null,
    // Nulled unless the lead source is Partnership Referral — enforced in the form.
    partnership_id: payload.partnership_id || null,
    zone_id: payload.zone_id || null,
    status: payload.status,
    date_of_invoice: payload.date_of_invoice || null,
    arrival_date: payload.arrival_date || null,
    arrival_time: payload.arrival_time || null,
    estimated_duration_minutes:
      payload.estimated_duration_minutes === "" ||
      payload.estimated_duration_minutes === null
        ? null
        : toInt(payload.estimated_duration_minutes),
    addresses: payload.addresses.map((a) => a.trim()).filter(Boolean),
    total_invoice_paid: toNum(payload.total_invoice_paid),
    pos_fee_percent: toNum(payload.pos_fee_percent),
    other_job_costs: toNum(payload.other_job_costs),
    total_worker_payout_override: toNullableNum(payload.total_worker_payout_override),
    invoice_ref: orNull(payload.invoice_ref),
    notes: orNull(payload.notes),
  };

  let jobId = payload.id;

  if (jobId) {
    const { error } = await supabase.from("jobs").update(row).eq("id", jobId);
    if (error) return fail(error.message);
  } else {
    // job_id is generated by the database sequence, seeded at 12.
    const { data, error } = await supabase.from("jobs").insert(row).select("id").single();
    if (error) return fail(error.message);
    jobId = data.id as string;
  }

  // Workers are rewritten wholesale; their fees cascade with them.
  const del = await supabase.from("job_workers").delete().eq("job_id", jobId);
  if (del.error) return fail(del.error.message);

  for (const [index, w] of payload.workers.entries()) {
    const { data, error } = await supabase
      .from("job_workers")
      .insert({
        job_id: jobId,
        entity_id: w.entity_id || null,
        regular_hours: toNum(w.regular_hours),
        regular_rate: toNum(w.regular_rate),
        travel_hours: toNum(w.travel_hours),
        travel_rate: toNum(w.travel_rate),
        other_hours: toNum(w.other_hours),
        other_rate: toNum(w.other_rate),
        total_pay_override: toNullableNum(w.total_pay_override),
        sort_order: index,
      })
      .select("id")
      .single();

    if (error) return fail(error.message);

    const fees = w.fees.filter((f) => orNull(f.description) || toNum(f.amount) !== 0);
    if (fees.length) {
      const { error: feeError } = await supabase.from("job_worker_fees").insert(
        fees.map((f, i) => ({
          job_worker_id: data.id,
          description: orNull(f.description),
          amount: toNum(f.amount),
          sort_order: i,
        })),
      );
      if (feeError) return fail(feeError.message);
    }
  }

  // Calendar is best-effort: a failure here surfaces as a warning, never a block.
  const { warning } = await syncJobCalendar(jobId);

  revalidatePath("/jobs", "layout");
  revalidatePath("/roster", "layout");
  revalidatePath("/dashboard");
  return { ok: true, id: jobId, warning };
}

export async function deleteJob(id: string): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.from("jobs").delete().eq("id", id);
  if (error) return fail(error.message);
  revalidatePath("/jobs", "layout");
  return { ok: true };
}
